name: story_teller_admin
description: "Story teller admin panel"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  app_bar_with_search_switch: ^1.8.5
  awesome_dialog: ^3.2.0
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  dropdown_button2: ^2.3.9
  flutter_html: ^2.2.1
  flutter_native_splash: ^2.2.0+1
  flutter_svg: ^0.23.0+1
  flutter_web_data_table: ^1.0.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.2.0
  intl: ^0.19.0
  introduction_screen: ^3.1.12
  line_awesome_flutter: ^2.0.0
  otp_text_field: ^1.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  string_validator: ^1.0.2
  timeago: ^3.6.1
  url_launcher: ^6.2.5
  image_picker_web: ^3.1.1
  firebase_core: ^2.27.0
  flutter_chat_bubble: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/banners/
    - assets/images/
    - assets/svg/

flutter_native_splash:
  image: assets/logo/logo.png
  color: "#ffffff"
  web_image_mode: center
  android_gravity: center
  ios_content_mode: center
# flutter pub run flutter_native_splash:create
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#ffffff"
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
# flutter pub run flutter_launcher_icons:main
