// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuyNIMmmZQos8frzktpSGGD53sGPIYk8E',
    appId: '1:184559588075:web:70dd750e9d1e3c1f9de4ae',
    messagingSenderId: '184559588075',
    projectId: 'storytelleradmin',
    authDomain: 'storytelleradmin.firebaseapp.com',
    storageBucket: 'storytelleradmin.appspot.com',
    measurementId: 'G-Q28S87J30B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGFWaSwH7CpZZGWg24LWFCtfnjpKtmREM',
    appId: '1:184559588075:android:656165381e67ec1b9de4ae',
    messagingSenderId: '184559588075',
    projectId: 'storytelleradmin',
    storageBucket: 'storytelleradmin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6nFvGur1o3hGmwZKv9IeEN7l_PTKkU-Y',
    appId: '1:184559588075:ios:ea65e15481b68e8d9de4ae',
    messagingSenderId: '184559588075',
    projectId: 'storytelleradmin',
    storageBucket: 'storytelleradmin.appspot.com',
    iosBundleId: 'com.storyteller.storyTellerAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6nFvGur1o3hGmwZKv9IeEN7l_PTKkU-Y',
    appId: '1:184559588075:ios:e569487b658ddde89de4ae',
    messagingSenderId: '184559588075',
    projectId: 'storytelleradmin',
    storageBucket: 'storytelleradmin.appspot.com',
    iosBundleId: 'com.storyteller.storyTellerAdmin.RunnerTests',
  );
}
